### ISSUE TITLE
Discord user integration

### ISSUE THREAD

**Issue by lieseldownes24** [gander-oceanic-fir-vatsim/czqo-core#11]
Integration with Discord will allow for the training system to communicate reminders to trainees, and other general purposes. 

- Use a bot to send messages to people
- Integrate joining the Discord with this system
- Allow for users to use their Discord pfp for their CZQO pfp
- Better integrate webhooks

**Comment by lieseldownes24** [comment]
https://github.com/laravel-notification-channels/discord

**Comment by lieseldownes24** [comment]
Discord user link complete
Discord join server complete

To-do:
Ban Discord users
Finish avatar sync
Name sync

**Comment by lieseldownes24** [comment]
Finished avatar sync, also reformed avatars in the process to be a users initials (like Apple) by default

**Comment by jordanhart0** [comment]
> Discord user link complete
> 
> Discord join server complete
> 
> 
> 
> To-do:
> 
> Ban Discord users
> 
> Finish avatar sync
> 
> Name sync

Hmm
