### ISSUE TITLE
ActivityBot specs and features

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#13]
Beginning from Feb 1st, ActivityCron shall monitor all controller activity for a month.

ActivityCron will then, on March 1st, purge all controllers who have not controlled at least one hour during that time.

Three days before March 1st, ActivityCron will send a friendly reminder to the controllers who have not yet fulfilled this one hour obligation.

ActivityCron will, from March 1st, begin to monitor normal activity. Controllers remaining on the roster after the purge will be obligated to control a further five hours before July 1st to meet the policy requirements.

ActivityCron will send friendly reminders to controllers exactly thirty days (one month), seven days (one week) and three days before July the 1st if they have not yet met this requirement. If they meet the requirement during the reminder period, do not send them further reminder emails.

If July 1st passes, all controllers who have not met the six hour activity requirement will be marked automatically by ActivityCron as 'inactive' on the roster.

Controllers marked inactive have six months (until Jan 1st, one full activity cycle) to renew themselves. I still need to decide how that happens.

After July 1st, ActivityCron resets, and begins to record another activity cycle, again sending three reminders at one month, one week and three days to controllers that have not met the obligation. ActivityCron will then perform another purge on Jan 1st, as well as removing controllers who need to be removed entirely from the roster.

ActivityCron will continue this cycle. Jan 1st -> July 1st, July 1st -> Jan 1st every year.

Workflow:

-First day of activity cycle
--ActivityCron marks controllers who did not meet the six hour requirement as inactive. 
--Deletes controllers who did not renew their certification

-ActivityCron monitors activity throughout the month, logging all connections, including duration, CID and position. 
-ActivityCron logs unauthorised connections in the same manner, additionally sending the FIR Chief an automated email if one is detected, every thirty minutes of that connection duration.

-Friendly reminders
--Thirty days before end of activity cycle
--Seven days before end of activity cycle
--Three days before end of activity cycle

ActivityCron will also display a friendly popup-in-corner reminder on the website each time a controller visits that hasn't met their requirements (after their first email reminder is sent)

**Comment by lieseldownes24** [comment]
@andrewogden1678 The `currency` field on the users table should be moved to the rostermember if you can since the users table is only meant to carry base information

**Comment by andrewogden1678** [comment]
Branched into multiple issues. Closing.
