### ISSUE TITLE
Social Media Stuff

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#14]
Twitter/Facebook icons (FontAwesome) on the top navbar next to the 'Login'/'Dashboard' buttons

Twitter RSS feed for @czqofirvatsim on twitter.

**Comment by andrewogden1678** [comment]
Icons done. RSS feed still to go.

**Comment by lieseldownes24** [comment]
I've applied for the Twitter dev account. I will need to move this to 1.8.0 because of application times and getting it implemented.
