### ISSUE TITLE
ActivityBot Source

### ISSUE THREAD

**Issue by rt-2** [gander-oceanic-fir-vatsim/czqo-core#16]
Hi,
Will you want to release the activityBot on it's own?
Thank you,
rt-2

**Comment by andrewogden1678** [comment]
Hi,

Once we're confident that the bot works as intended we can consider releasing standalone code for it.

Cheers,
Andrew

**Comment by rt-2** [comment]
Why not developing it open source? You might get some help.
I understand maybe its nested into your script or you must have your reason.

**Comment by andrewogden1678** [comment]
It is open source, you can find the code under Console/Kernel.php. What I meant by 'standalone' is as a PHP package to insert into an existing laravel project.

**Comment by lieseldownes24** [comment]
We can open it up to other FIRs anyway, obviously when we've tested it though

**Comment by rt-2** [comment]
I am not using Laravel actually I'm bare PHP, thanks for the hint on the location.

**Comment by andrewogden1678** [comment]
I can also confirm that the connection logging code does work as intended.

**Comment by lieseldownes24** [comment]
I don't know why this is a seperate issue, making a proper activitybot one
