### ISSUE TITLE
Sharpen blown-up logo image on website

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#21]
I can literally count the number of pixels in the logo here 
![image](https://user-images.githubusercontent.com/31175571/80897184-9b841b80-8d39-11ea-96d8-3df4a9dd72dd.png)

**Comment by lieseldownes24** [comment]
https://github.com/gander-oceanic-fir-vatsim/czqo-core/commit/9a29006181c5f3704cb9ba202e0f93fa04472c8a
