### ISSUE TITLE
Activity not met emails (ActivityBot)

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#25]
Send emails 1 month, 2 weeks and 1 week before activity is due if not already completed.

**Comment by andrewogden1678** [comment]
Also display popup on website on each first visit after being sent an email

**Comment by andrewogden1678** [comment]
Do a job for this

**Comment by andrewogden1678** [comment]
- [ ] Laravel job created

- [ ] Send email to Andrew with button to review and a button to process inactivity (automation is dangerous for obvious reasons). Have a webpage to achieve the same thing

**Comment by lieseldownes24** [comment]
Closing this issue for 1.7.0 and making a new one
