### ISSUE TITLE
Pilots dropdown should automatically link to https://ganderoceanic.com/pilots

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#28]
Users should be able to simply click on the pilots dropdown button and be led to the pilots link

**Comment by lieseldownes24** [comment]
added as agreed in #web-team on discord https://github.com/gander-oceanic-fir-vatsim/czqo-core/commit/5f01c56da26249ec7c104690e0d8b98951d3c5d8
