### ISSUE TITLE
News should be separate to the 'publications' dropdown (see image)

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#31]
Perhaps its own button on the navbar, even
![image](https://user-images.githubusercontent.com/31175571/81125477-97474080-8f7b-11ea-91cd-6a0da815dbed.png)

**Comment by lieseldownes24** [comment]
(Fixed)[https://github.com/gander-oceanic-fir-vatsim/czqo-core/commit/f52becc6d2eed3447ecfbb56c3092d7f73484538]
