### ISSUE TITLE
Avatars need to be round (new controllers div)

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#33]
![image](https://user-images.githubusercontent.com/31175571/81158656-89b9a700-8fcb-11ea-961c-0fbac11d7945.png)

**Comment by lieseldownes24** [comment]
https://github.com/gander-oceanic-fir-vatsim/czqo-core/commit/685cd81b6d4ac247351eb15c0bd737449f315334
