### ISSUE TITLE
Randomise banner images on dashboard

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#34]
Have a set of images that get chosen at random for the banner each time the user opens their dashboard, similar to the 'hello' function. Choose images from screenshots channel.

**Comment by lieseldownes24** [comment]
https://github.com/gander-oceanic-fir-vatsim/czqo-core/commit/64d6fb3e97916f68a7dbe61a8d8aeae8bba76c48
