### ISSUE TITLE
Make the 'about the website' page more visible

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#40]
![image](https://user-images.githubusercontent.com/31175571/81369115-f308f980-9134-11ea-8707-dd6d884f3647.png)

Also include github and canary links.

**Comment by lieseldownes24** [comment]
https://github.com/gander-oceanic-fir-vatsim/czqo-core/commit/e896a2b4ff7e3dfe51d871555462ba2bfaf89d47 https://github.com/gander-oceanic-fir-vatsim/czqo-core/commit/b172ceb25ee2607029c89c7b7c7f72bf53ad7dc0
