### ISSUE TITLE
Sectors on website map broken

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#42]
![image](https://user-images.githubusercontent.com/31175571/81370455-8abc1700-9138-11ea-964e-48d744c0f84d.png)
There's nobody currently online yet both sectors display. Also when only one controller is online, both sectors display. 

Perhaps map could also say who is controlling the sectors (on hover)

**Comment by lieseldownes24** [comment]
https://discordapp.com/channels/479250337048297483/705564444188606584/708244191909642260
