### ISSUE TITLE
Fix white on white/transparent backgrounds on branding page

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#50]
![image](https://user-images.githubusercontent.com/31175571/81495110-390abc80-92f1-11ea-8e4c-9ee7689eda2a.png)

**Comment by lieseldownes24** [comment]
1.6.1 release https://github.com/gander-oceanic-fir-vatsim/czqo-core/commit/d98fc4dc67872a68f951f9c35999705c27d64549
