### ISSUE TITLE
Investigate abnormal CDN behaviour (avatars and news banners)

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#52]
![image](https://user-images.githubusercontent.com/31175571/81500208-f27a8980-9313-11ea-94dc-976bb3b70d40.png)
![image](https://user-images.githubusercontent.com/31175571/81500211-f60e1080-9313-11ea-9680-744540951067.png)

**Comment by andrewogden1678** [comment]
All avatars are broken except those sourced from Discord 
![image](https://user-images.githubusercontent.com/31175571/81512950-0059fa00-9368-11ea-9b97-a22048a35da2.png)

**Comment by lieseldownes24** [comment]
Should be fixed - the storage folder didn't copy over correctly
