### ISSUE TITLE
Fix timelapse playing only once

### ISSUE THREAD

**Issue by andrewogden1678** [gander-oceanic-fir-vatsim/czqo-core#53]
TTSIA

Fix and append new version number 1.6.1, update changelog. Also include issue [https://github.com/gander-oceanic-fir-vatsim/czqo-core/issues/52](url) in the 1.6.1 hotfix. @lieseldownes24

**Comment by andrewogden1678** [comment]
@lieseldownes24 news on this?

**Comment by lieseldownes24** [comment]
https://github.com/gander-oceanic-fir-vatsim/czqo-core/commit/13a8e0bdba8890d5261a8e0b3628fde6a0b03c2d
